### PR TITLE
More work

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] remove process.cwd() support for tsconfig, this wont work with nested builds and process.cwd() isn't guarented to be a specific root.
- [x] some cleanup
- [x] add thorough tests
- [x] provide node resolution algorithm compatible auto tsconfig.json loading

### CODE REVIEW

**Comment by chancancode** [comment]
I think @wycats will be :-1: on rm-ing auto tsconfig

**Comment by stefanpenner** [comment]
> I think @wycats will be  on rm-ing auto tsconfig

but the feature does not work, and doesn't really make sense (not via just `process.cwd()`).

**Comment by wycats** [comment]
@stefanpenner how are you supposed to talk about "project root" in Broccoli?

If the answer is "you don't", that's pretty unacceptable.

**Comment by stefanpenner** [comment]
> If the answer is "you don't", that's pretty unacceptable.
> 
> @stefanpenner how are you supposed to talk about "project root" in Broccoli?

I don't think you want to reference project root here, what you likely want is to reference the root of the invoking node_module.

given:

```
project/node_module/a
project/node_module/b
```

Where `a` is using typescript, searching for the tsconfig in `project` seems incorrect. As this leaks specifics of `a` into `project`, potentially conflicting in `project` and `b`.

If for example, we want to publish an ember-addon authored using TS, it should by default be self contained. One can easily imagine multiple ember-addon's using TS, but with incompatible configuration...

@wycats it should be possible to implement the correct approach, I'll take a stab at it in the AM.

**Comment by chancancode** [comment]
Looks great! All the cleanup :heart_eyes:

**Comment by stefanpenner** [comment]
will fix the failure in-abit.

**Comment by stefanpenner** [comment]
although the tests are green, manually testing in tildeio/glimmer suggests something else is still wrong, will investigate and try and track down whatsup.

**Comment by stefanpenner** [comment]
fixed

**Comment by chancancode** [comment]
There appears to be one more failing test!

**Pull request merged**
